---
shared:
  # We specify a common NodeJS Docker image for our Jobs
  # Docker image - https://hub.docker.com/r/library/node/
  image: node:8

jobs:
  main:
    # Requires is a single job name or array of job names that will trigger the job to run.
    requires: [~pr, ~commit]
    # Steps is the ordered list of commands to execute.
    steps:
      - install: npm install
      - test: npm test
  publish:
    requires: main
    steps:
      - set_access: npm config set access public > /dev/null 2>&1
      - set_token: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN > /dev/null 2>&1
      - publish_npm: npm publish
    secrets:
      - NPM_TOKEN
